server.port=${PORT:80}
spring.cloud.discovery.enabled=false
eureka.client.enabled=false
spring.datasource.url=${KAARIGAR_DATABASE_URL}
spring.datasource.username=${KAARIGAR_DATABASE_USERNAME}
spring.datasource.password=${KAARIGAR_DATABASE_PASSWORD}
spring.jpa.show-sql=false
internal.service.secret=${INTERNAL_SERVICE_SECRET}
services.auth-url=${AUTH_SERVICE_URL}
services.event-url=${EVENT_SERVICE_URL}
media.max-upload-size-bytes=4194304
spring.servlet.multipart.max-file-size=4MB
spring.servlet.multipart.max-request-size=4.5MB

spring.jpa.hibernate.ddl-auto=update
