spring.application.name=KAARIGAR-SERVICE
server.port=8083

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/kaarigar_artisan
spring.datasource.username=postgres
spring.datasource.password=admin

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Eureka
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

internal.service.secret=KaarigarExpoInternalSecret2026
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=10MB
media.storage-dir=uploads
