server.port=${PORT:80}
spring.cloud.discovery.enabled=false
eureka.client.enabled=false
spring.datasource.url=${AUTH_DATABASE_URL}
spring.datasource.username=${AUTH_DATABASE_USERNAME}
spring.datasource.password=${AUTH_DATABASE_PASSWORD}
spring.jpa.show-sql=false
jwt.secret=${JWT_SECRET}
internal.service.secret=${INTERNAL_SERVICE_SECRET}

spring.jpa.hibernate.ddl-auto=update
