server.port=${PORT:80}
app.frontend-url=${FRONTEND_URL}
app.email.enabled=${EMAIL_ENABLED:true}
app.email.from=${EMAIL_FROM}
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS:true}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}
spring.cloud.discovery.enabled=false
eureka.client.enabled=false
spring.datasource.url=${AUTH_DATABASE_URL}
spring.datasource.username=${AUTH_DATABASE_USERNAME}
spring.datasource.password=${AUTH_DATABASE_PASSWORD}
spring.jpa.show-sql=false
jwt.secret=${JWT_SECRET}
internal.service.secret=${INTERNAL_SERVICE_SECRET}

spring.jpa.hibernate.ddl-auto=update
