server.port=${PORT:80}
spring.cloud.discovery.enabled=false
eureka.client.enabled=false

spring.cloud.gateway.server.webmvc.routes[0].uri=${AUTH_SERVICE_URL}
spring.cloud.gateway.server.webmvc.routes[1].uri=${EVENT_SERVICE_URL}
spring.cloud.gateway.server.webmvc.routes[2].uri=${KAARIGAR_SERVICE_URL}
spring.cloud.gateway.server.webmvc.routes[3].uri=${VISITOR_SERVICE_URL}
spring.cloud.gateway.server.webmvc.routes[4].uri=${KAARIGAR_SERVICE_URL}

spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedOriginPatterns[0]=${CORS_ALLOWED_ORIGIN_PATTERN:https://*.vercel.app}
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedMethods[4]=OPTIONS
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedHeaders[0]=*

jwt.secret=${JWT_SECRET}
