server.port=${PORT:80}
spring.cloud.discovery.enabled=false
eureka.client.enabled=false
spring.datasource.url=${VISITOR_DATABASE_URL}
spring.datasource.username=${VISITOR_DATABASE_USERNAME}
spring.datasource.password=${VISITOR_DATABASE_PASSWORD}
spring.jpa.show-sql=false
internal.service.secret=${INTERNAL_SERVICE_SECRET}
services.event-url=${EVENT_SERVICE_URL}
services.visitor-url=http://127.0.0.1:${PORT:80}
