server.port=${PORT:80}
spring.cloud.discovery.enabled=false
eureka.client.enabled=false
spring.datasource.url=${EVENT_DATABASE_URL}
spring.datasource.username=${EVENT_DATABASE_USERNAME}
spring.datasource.password=${EVENT_DATABASE_PASSWORD}
spring.jpa.show-sql=false
internal.service.secret=${INTERNAL_SERVICE_SECRET}
services.auth-url=${AUTH_SERVICE_URL}
services.kaarigar-url=${KAARIGAR_SERVICE_URL}
services.visitor-url=${VISITOR_SERVICE_URL}

spring.jpa.hibernate.ddl-auto=update
